import sys
import random
import time
import requests
from PyQt5.QtCore import QUrl, QSettings
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout
from PyQt5.QtWebEngineWidgets import QWebEngineView
from fake_useragent import UserAgent

USER_AGENT_LIST = [
    # Add your desired user agents here, or you can find pre-built lists online.
    # Example user agents (You can expand this list with more options):
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/90.0.818.62 Safari/537.36 Edg/90.0.818.62",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Version/14.1 Safari/537.36",
]

def get_random_user_agent():
    return random.choice(USER_AGENT_LIST)

def get_hidden_browser_info(url):
    ua = UserAgent()
    user_agent = ua.random  # Use the random user agent generated by fake_useragent

    headers = {
        "User-Agent": user_agent,
        "DNT": "1"  # Force Do Not Track
    }

    try:
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()  # Raise an exception for HTTP errors (e.g., 404, 500)
        time.sleep(5)  # Wait for the page to load completely (you can adjust the sleep time as needed)
        return response.text
    except requests.RequestException as e:
        print("Error fetching the URL:", e)
        return None

class WebBrowser(QMainWindow):
    def __init__(self):
        super().__init__()

        self.init_ui()

    def init_ui(self):
        self.setWindowTitle("Secure Web Browser")
        self.setGeometry(100, 100, 800, 600)

        # Apply settings to disable JavaScript and WebGL
        settings = QSettings()
        settings.setValue("WebGLEnabled", False)
        settings.setValue("JavascriptEnabled", False)

        self.central_widget = QWidget(self)
        self.setCentralWidget(self.central_widget)

        self.layout = QVBoxLayout(self.central_widget)

        self.web_view = QWebEngineView()
        self.layout.addWidget(self.web_view)

        target_url = "https://duckduckgo.com"  # Replace with the desired URL
        page_source = get_hidden_browser_info(target_url)
        if page_source:
            self.web_view.setHtml(page_source, baseUrl=QUrl(target_url))

if __name__ == "__main__":
    app = QApplication(sys.argv)
    browser = WebBrowser()
    browser.show()
    sys.exit(app.exec_())
